language: objective-c
osx_image: xcode8.3

install:
  - cd example && npm install && cd ..
  - cd example/ios && pod install && cd ../..
  - cd example && ./node_modules/.bin/react-native link react-native-analytics-segment-io && cd ..

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace example/ios/example.xcworkspace -scheme example CODE_SIGNING_REQUIRED=NO
